image: node:20-alpine

stages:
  - lint:commit
  - lint:code
  - test
  - merge
  - release

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  GITLAB_TOKEN: ${NPM_ACCESS_TOKEN}

before_script:
  - npm ci --cache .npm --prefer-offline

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

lint:commit:
  stage: lint:commit
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint

lint:code:
  stage: lint:code
  script:
    - ./node_modules/eslint/bin/eslint.js $(git diff --name-only HEAD | grep -E 'src/.*\.ts|test/.*\.ts$' | xargs)

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm run test-ci

approve:
  stage: merge
  script:
    - echo ok
  when: manual
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

release:
  stage: release
  before_script:
    - apk update && apk upgrade && \
    - apk add --no-cache bash git openssh
  script:
    - cp .gitlab/npmrc .npmrc
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
