image: node:latest

stages:
- lint:commit
- lint:code
- test
- release

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  GITLAB_TOKEN: ${NPM_ACCESS_TOKEN}

before_script:
  - npm ci --cache .npm --prefer-offline

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

lint:commit:
  stage: lint:commit
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint

lint:code:
  stage: lint:code
  script:
    - ./node_modules/eslint/bin/eslint.js $(git diff --name-only HEAD | grep -E 'src/.*\.ts|test/.*\.ts$' | xargs)

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

release:
  stage: release
  script:
    - cp .gitlab/npmrc .npmrc
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
