image: node:20-alpine

stages:
  - lint:commit
  - lint:code
  - test
  - merge
  - release

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}
  GITLAB_TOKEN: ${NPM_ACCESS_TOKEN}

before_script:
  - npm ci --cache .npm --prefer-offline

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/

lint:commit:
  stage: lint:commit
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: manual
      allow_failure: false

lint:code:
  stage: lint:code
  script:
    - ./node_modules/eslint/bin/eslint.js $(git diff --name-only HEAD | grep -E 'src/.*\.ts|test/.*\.ts$' | xargs)
  rules:
    - when: always

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm run test-ci
  rules:
    - when: always

approve:
  stage: merge
  script:
    - echo ok
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - when: manual
      allow_failure: false

release:
  stage: release
  before_script:
    - apk update && apk upgrade && \
    - apk add --no-cache bash git openssh
  script:
    - cp .gitlab/npmrc .npmrc
    - ./node_modules/.bin/semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
